name: torch_cuda
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - aom=3.4.0
  - attr=2.5.2
  - blas=2.116
  - blas-devel=3.9.0
  - blessed=1.22.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cairo=1.16.0
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - contourpy=1.3.3
  - cpython=3.11.14
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.9
  - cycler=0.12.1
  - dbus=1.16.2
  - expat=2.7.1
  - ffmpeg=4.4.2
  - fftw=3.3.10
  - filelock=3.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freetype=2.14.1
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - giflib=5.2.2
  - glib=2.86.0
  - glib-tools=2.86.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.7.6
  - gpustat=1.1.1
  - graphite2=1.3.14
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.41
  - h2=4.3.0
  - harfbuzz=6.0.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=70.1
  - idna=3.11
  - jack=1.9.22
  - jinja2=3.1.6
  - jpeg=9e
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.14.1.1
  - libcups=2.3.3
  - libcurand=10.3.10.19
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdb=6.2.32
  - libdeflate=1.17
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libevent=2.1.10
  - libexpat=2.7.1
  - libffi=3.5.2
  - libflac=1.4.3
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgcrypt=1.11.1
  - libgcrypt-devel=1.11.1
  - libgcrypt-lib=1.11.1
  - libgcrypt-tools=1.11.1
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.0
  - libgomp=15.2.0
  - libgpg-error=1.55
  - libhwloc=2.9.1
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libltdl=2.4.3a
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libogg=1.3.5
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=15.3
  - libsndfile=1.2.2
  - libsqlite=3.50.4
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=253
  - libtasn1=4.20.0
  - libtiff=4.5.0
  - libtool=2.5.4
  - libudev1=253
  - libunistring=0.9.10
  - libuuid=2.41.2
  - libva=2.18.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - markupsafe=3.0.3
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.5
  - nettle=3.8.1
  - networkx=3.5
  - nspr=4.37
  - nss=3.117
  - numpy=2.3.4
  - nvidia-ml-py=13.580.82
  - openh264=2.3.0
  - openjpeg=2.5.0
  - openssl=3.1.8
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.46
  - pillow=9.4.0
  - pip=25.2
  - pixman=0.46.4
  - ply=3.11
  - psutil=7.1.2
  - pthread-stubs=0.4
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pycparser=2.22
  - pyparsing=3.2.5
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.11.6
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.3
  - qhull=2020.2
  - qt-main=5.15.8
  - readline=8.2
  - requests=2.32.5
  - setuptools=80.9.0
  - sip=6.7.12
  - six=1.17.0
  - svt-av1=1.2.0
  - sympy=1.14.0
  - tbb=2021.9.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.3.0
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tornado=6.5.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
